version: "3.9"

services:
  store-service:
    image: store-service
    ports:
      - 50051:50051
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./database:/data
    hostname:
      mongodb

  envoy:
    image: envoyproxy/envoy-dev:latest
    ports:
      - "10000:10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
