micronaut:
  executors:
    number-of-threads: 4
grpc:
  host: 'localhost'
  port: '50052'

mongodb:
  uri: mongodb://localhost:27017
## Use uri: mongodb://mongodb:27017 for docker-compose deployment.

kafka:
  bootstrap:
    servers:
      - localhost:29092
#  producers:
#    default:
#      retries: 5