version: '3.7'

services:
  envoy:
    image: envoyproxy/envoy-dev:a63b899a6d7f5c655c0c76404987ab106ad02c13
    ports:
      - "10000:10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./database:/data
    networks:
      - bridge
    hostname:
      mongodb

networks:
  bridge:
